http:
  port: ${PORT:-3333}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  weather:
    host: localhost
    paths: "/onecall"
  geo:
    host: localhost
    paths: "/reverse"

serviceEndpoints:
  httpWeather:
    url: "https://api.openweathermap.org/data/2.5"
  httpGeo:
    url: "https://api.openweathermap.org/geo/1.0"

policies:
  - cors
  - expression
  - log
  - proxy
pipelines:
  weather:
    apiEndpoints:
      - weather
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpWeather
              changeOrigin: true
  geo:
    apiEndpoints:
      - geo
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpGeo
              changeOrigin: true
