http:
  port: ${PORT:-3333}
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  weather:
    host: api-gateway-clima-tempo.herokuapp.com
    methods: "GET"
    paths: "/onecall"
  geo:
    host: api-gateway-clima-tempo.herokuapp.com
    methods: "GET"
    paths: "/reverse"

serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  httpWeather:
    url: "https://api.openweathermap.org/data/2.5"
  httpGeo:
    url: "https://api.openweathermap.org/geo/1.0"

policies:
  - cors
  - expression
  - log
  - proxy
pipelines:
  defaul:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true

  weather:
    apiEndpoints:
      - weather
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpWeather
              changeOrigin: true
  geo:
    apiEndpoints:
      - geo
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpGeo
              changeOrigin: true
